version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "developers"
      POSTGRES_USER: "devuser"
      POSTGRES_PASSWORD: "pgpwd4dev"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"